# Generated by Django 2.2.24 on 2022-11-03 22:42

from django.db import migrations


def set_field_new_building(apps, scheme_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.new_building = True if flat.construction_year >= 2015 else False
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [migrations.RunPython(set_field_new_building)]
