# Generated by Django 2.2.24 on 2022-11-05 19:50

from django.db import migrations

import phonenumbers

def normalize_user_phone_numbers(apps, scheme_editor):
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all().iterator():
        flat_owners_phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(flat_owners_phonenumber):
            flat.owner_pure_phone = flat_owners_phonenumber
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_user_phone_numbers),
    ]
