# Generated by Django 2.2.24 on 2022-11-05 21:24

from django.db import migrations


def migrate_flatowners_to_owner(apps, scheme_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all().iterator():
        Owner.objects.get_or_create(owner_fullname=flat.owner,
                                    owners_phonenumber=flat.owners_phonenumber,
                                    owner_pure_phone=flat.owner_pure_phone)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20221106_0017'),
    ]

    operations = [
        migrations.RunPython(migrate_flatowners_to_owner),
    ]
