# Generated by Django 2.2.24 on 2022-11-07 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20221107_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner_fullname',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='pure_phone',
        ),
    ]
